build.id=30303050
build.version=1.2.3
#build.name=Git-Production-Build 1234
build.name={cipher}AQAiey4YNlqQdPDFbhso/53k8dn8HobICmrbMSOsFqDlEulebGpaPkw0h9HHE3op5LfhuOI9Esp2Y0d5No+SVq3EWppsRooh2ixvHFDd9uN/SDquMbicxx5V1mw4qXVHjcS2bZqCl9FNkkxKwp+8GKjHruRHtVal1BXkcyD4cEvaXYFfQ+YJ/oR5Lcbp455Dk5SnGMxd39bAacWIFXby49QUW4XC+P2dGucyx6usSYCb/JY9EosXBnPAeejkeb7mohKvN4CIq2aur/LxP2GAx1PUoy0NZ5hAA+kJQNYI6Gqm+dphQf66M41j5C7DhPO9+9B4L70u9ZGgKt5+/ci5X1Op8/KMVvcSDm2Y45lMhSxiLIUlGMfGhAOudGh3ecjVtxpC35UmHQcMBXO9nyQ9IqSe
build.type=Git Production Build

#for spring cloud refresh
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
management.endpoints.web.exposure.include=*
