build.id=202020
build.version=1.2.3
build.name={cipher}AQCM6R+mD+gKcJZVmcPpkj7WLsQ6oIPmwOs+aqNoAAbwfF6ZMjmAMtawv7UBelTr113yxST/4r6GBrxykXnYsT9bl8HuFvXkaldK4sel9/t5ely1zSWdp2C6VArgrxbGTWYQCrDFLCOoyvzeQW9hkMN6C8cQO4meM//943k71ES/jX0glfNTOcAyb6u8OmwV8UtBvxVlsZQzFVjh6NkCKTm6e4ywQLm1z3Q1hHhcG3wP8rTj034qivLbddQntlA7qKWt6FsB6sM9+11xDsFQ0J0Pxp34TDMVUhLJ4s2JhC9OMXEAAvnxm7mst5N+mSyr7JM9R9EwTx8stltSiZgt3ear8v52sIsUZMP420sgBBePay1XJ74x1FaLH69CwyKL6jaZ7nHgOeY/Qa/ywpTOb9Ab
build.type=Git-Devlopment Build

#for spring cloud refresh
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
management.endpoints.web.exposure.include=*
